name: Test
on:
  push:
    branches:
      - 'master'
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.x"

      - name: Set up Poetry
        uses: snok/install-poetry@v1
        with:
          version: "1.1.13"

      - name: Set up cache
        uses: actions/cache@v2
        id: cache-venv
        with:
          path: /home/runner/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Install cookiecutter
        run: make install

      - name: Create a new dipdup project and ensure it's valid
        run: poetry run cookiecutter --no-input . && cd my-dipdup-indexer && make all